#Exclude:
#- 'db/schema.rb'
#- 'vendor/**/*'

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 79

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/MethodLength:
  Max: 20

