#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'example'

class LabelExample < Example
  def self.parse_opts(opts, param)
    opts.banner = 'Usage: label_ex.rb [options]'

    param.x_value = Slithernix::Cdk::CENTER
    param.y_value = Slithernix::Cdk::CENTER
    param.box = true
    param.shadow = true
    super
  end

  # This program demonstrates the Cdk label widget.
  def self.main
    # Declare variables.

    params = parse(ARGV)

    # Set up CDK
    curses_win = Curses.init_screen
    cdkscreen = Slithernix::Cdk::Screen.new(curses_win)

    # Set up CDK colors
    Slithernix::Cdk::Draw.init_color

    # Set the labels up.
    mesg = [
      '<C></202/B>This line should be CENTERED and BOLD with color pair 202.',
      '<C></33/B>This line should be CENTERED and BOLD with color pair 33.',
      '<C></135/B>This line should be CENTERED and BOLD with color pair 135.',
      '<C>This line should be CENTERED and set to whatever the screen default is.'
    ]

    # Declare the labels.
    demo = Slithernix::Cdk::Widget::Label.new(cdkscreen,
                                              params.x_value, params.y_value, mesg, 4,
                                              params.box, params.shadow)

    # if (demo == 0)
    # {
    #   /* Clean up the memory.
    #   destroyCDKScreen (cdkscreen);
    #
    #   # End curses...
    #   end_cdk ();
    #
    #   printf ("Cannot create the label. Is the window too small?\n");
    #   ExitProgram (EXIT_FAILURE);
    # }

    # Draw the CDK screen.
    cdkscreen.refresh
    demo.wait(' ')

    # Clean up
    demo.destroy
    cdkscreen.destroy
    Slithernix::Cdk::Screen.end_cdk
    # ExitProgram (EXIT_SUCCESS);
  end
end

LabelExample.main
